// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIewekU6DDUCQryI7G28mbFS139EF-nCI',
    appId: '1:638015560823:web:7fd1fa09e918539d603a72',
    messagingSenderId: '638015560823',
    projectId: 'notar-4dde5',
    authDomain: 'notar-4dde5.firebaseapp.com',
    storageBucket: 'notar-4dde5.appspot.com',
    measurementId: 'G-DMGVH85QX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDI8t9LxADgJ9PFicsFD4pud8vlR-Zy90',
    appId: '1:638015560823:android:683e701844911204603a72',
    messagingSenderId: '638015560823',
    projectId: 'notar-4dde5',
    storageBucket: 'notar-4dde5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3wgZaNR9SZVPCKW_tvjIdQpehPJe1GgA',
    appId: '1:638015560823:ios:1b3af515c99c0894603a72',
    messagingSenderId: '638015560823',
    projectId: 'notar-4dde5',
    storageBucket: 'notar-4dde5.appspot.com',
    androidClientId: '638015560823-sjej5vql5gfr5pj82438tmoffeoq3rv9.apps.googleusercontent.com',
    iosClientId: '638015560823-dvp1i3tf538u9v4vqvlce0ddqa0r0pes.apps.googleusercontent.com',
    iosBundleId: 'com.ronary.notary-app',
  );
}
